# Generated by Django 5.2.7 on 2025-10-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userlist_listitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="listitem",
            name="movie_title",
            field=models.CharField(
                default="unknown", max_length=255, verbose_name="movie_title"
            ),
            preserve_default=False,
        ),
    ]
