# Generated by Django 6.0b1 on 2025-11-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userlist_listitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listitem",
            old_name="name",
            new_name="movie_name",
        ),
    ]
